- name: Stop service systemd-resolved
  become: yes
  ansible.builtin.service:
    name: systemd-resolved
    state: stopped

- name: Disable service systemd-resolved
  become: yes
  ansible.builtin.service:
    name: systemd-resolved
    enabled: no

- name: Remove symbol link resolv.conf
  become: yes
  ansible.builtin.file:
    path: /etc/resolv.conf
    state: absent

- name: resolv.conf | Ensure dns configuration
  become: yes
  template:
    src: resolv.j2
    dest: "/etc/resolv.conf"
    owner: root
    group: root
    mode: 0644