---
- name: Common | Override default data with user one
  set_fact:
    s_cd: "{{ server_common_data | combine(server_common_group, server_common_host, recursive=True) }}"

- name: Common | Packages installation
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ s_cd.packages }}"

- name: Common | Set hostname
  hostname:
    name: "{{ s_cd.dns_hostname }}"

- name: Common | Users
  include_tasks: users.yml
