---
- name: Collect old ssh keys
  find:
    paths: /etc/ssh
    patterns: ssh_host_*
  register: ssh_keys

- name: Delete old ssh keys
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ ssh_keys.files }}"

- name: Generate new ssh host keys
  shell:
    cmd: |
      dpkg-reconfigure openssh-server

- name: Restart sshd service
  systemd:
    state: restarted
    name: sshd
