---
- name: Common | SSH keys | Set {{ user.key }} keys
  authorized_key:
    user: "{{ user.value.name }}"
    key: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items: "{{ user.value.ssh_keys }}"
  when: user.value.ssh_keys is defined and user.value.state != 'absent'
  tags:
    - ssh_keys
