---
- name: Ensure systemd configuration directory
  become: yes
  file:
    state: directory
    path: /etc/systemd/journald.conf.d
    owner: root
    group: root
    mode: 0755

- name: Ensure systemd configuration
  become: yes
  copy:
    content: |
      [Journal]
      Storage=persistent
    dest: /etc/systemd/journald.conf.d/00-override.conf
    owner: root
    group: root
    mode: 0755
  notify: Restart systemd
