---
- name: Common | Users | Ensure users on target node
  user:
    name: "{{ user.value.name }}"
    comment: "{{ user.value.comment | default('') }}"
    groups: "{{ user.value.groups | default('') }}"
    append: yes
    createhome: yes
    remove: "{{ user.value.absent | default(False) }}"
    state: "{{ user.value.state | default('present') }}"
    password: "{{ user.value.password }}"
    shell: /bin/bash
  no_log: yes
  tags:
    - users

- name: Common | SSH keys | Get user home directory
  shell:
    cmd: |
      getent passwd "{{ user.value.name }}" | cut -d':' -f6
  register: passwd_user
  changed_when: false
  tags:
    - users
    - ssh_keys

- name: Common | Users | Ensure user bashrc file
  copy:
    src: skel/.bashrc
    dest: "{{ passwd_user.stdout }}/.bashrc"
    owner: "{{ user.value.name }}"
    group: "{{ user.value.name }}"
    mode: 0644
  when: user.value.state == 'present'
  tags:
    - users

- name: Common | Users | Ensure user irbrc file
  copy:
    src: skel/.irbrc
    dest: "{{ passwd_user.stdout }}/.irbrc"
    owner: "{{ user.value.name }}"
    group: "{{ user.value.name }}"
    mode: 0644
  when: user.value.state == 'present'
  tags:
    - users
