---
- name: Common | Users | Ensure users on target node
  user:
    name: "{{ item.value.name }}"
    comment: "{{ item.value.comment | default('') }}"
    groups: "{{ item.value.groups | default('') }}"
    append: yes
    createhome: yes
    remove: "{{ item.value.absent | default(False) }}"
    state: "{{ item.value.state | default('present') }}"
    password: "{{ item.value.password }}"
    shell: /bin/bash
  with_dict: "{{ s_cd.users }}"
  no_log: yes
  tags:
    - users

- name: Common | Users | Ensure user bashrc file
  copy:
    src: skel/.bashrc
    dest: "/home/{{ item.value.name }}/.bashrc"
    owner: "{{ item.value.name }}"
    group: "{{ item.value.name }}"
    mode: 0644
  no_log: yes
  with_dict: "{{ s_cd.users }}"
  when: item.value.state == 'present'

- name: Common | Users | Ensure root bashrc file
  copy:
    src: skel/.bashrc
    dest: "/root/.bashrc"
    owner: root
    group: root
    mode: 0640

- name: Common | Users | Ensure user irbrc file
  copy:
    src: skel/.irbrc
    dest: "/home/{{ item.value.name }}/.irbrc"
    owner: "{{ item.value.name }}"
    group: "{{ item.value.name }}"
    mode: 0644
  no_log: yes
  with_dict: "{{ s_cd.users }}"
  when: item.value.state == 'present'

- name: Common | Users | Ensure root irbrc file
  copy:
    src: skel/.irbrc
    dest: "/root/.irbrc"
    owner: root
    group: root
    mode: 0640
