---
- name: Common | Users | Ensure users on target node
  user:
    name: "{{ item.value.name }}"
    comment: "{{ item.value.comment | default('') }}"
    groups: "{{ item.value.groups | default('') }}"
    append: yes
    createhome: yes
    remove: "{{ item.value.absent | default(False) }}"
    state: "{{ item.value.state | default('present') }}"
    password: "{{ item.value.password }}"
    shell: /bin/bash
  with_dict: "{{ s_cd.users }}"
  no_log: yes
  tags:
    - users
